/*
Consider the following algorithm
Start with a positive number n
If n is even, then divide by 2
If n is odd, then multiply by 3 and add 1
Repeat above two steps until n becomes 1
The sequence generated by above algorithm is called Ascol sequence.
For example, if the Ascol sequence of the number 7 is computed as
7, 22, 11. 34, 17, 52, 26, 13, 40, 20, 10,5 16, 8,4,2,1
Write a C program with function named isAscolSequence () that takes an array 
as argument and tests whether the contains Ascol sequence or not.
*/

#include <stdio.h>

int sizeOfArray;
int isAscolSequence(int arr[], int);
int main(){

    printf("Enter the numbers of elements in the sequence: ");
    scanf("%d", &sizeOfArray);

    int seq[sizeOfArray];
    printf("Enter the elements of the sequence: ");
    for (int i = 0; i < sizeOfArray;i++)
        scanf("%d", &seq[i]);

    int num;
    printf("Enter the number to generate the sequence and match with: ");
    scanf("%d", &num);

    int bool = isAscolSequence(seq, num);

    if(bool)
        printf("The given sequence is Ascol Sequence of %d.", num);
    else 
        printf("The given sequence is not Ascol Sequence of %d.", num);

    return 0;
}

int isAscolSequence(int arr[],int num){
    int temp = num;
    int flag=0;
    for (int i = 0; temp != 1; i++)
    {
        for(int j = 0; j<sizeOfArray; j++)
            if (arr[j]==temp)
                flag = 1;

        if (!flag)
            return 0;

        temp = (temp % 2)? ((temp * 3)+1) : temp / 2;
    }
    return 1;
}

/*
Enter the numbers of elements in the sequence: 17
Enter the elements of the sequence: 7 22 11 34 17 52 26 13 40 20 10 5 16 8 
                                    4 2 1
Enter the number to generate the sequence and match with: 7
The given sequence is Ascol Sequence of 7.
*/